<?php
session_start();
require '../../dompdf/autoload.inc.php';
use Dompdf\Dompdf;
use Dompdf\Options;

include('../../config/db.php');

if (!isset($_SESSION['username']) || $_SESSION['role'] !== 'Admin') {
    die("Access denied.");
}

if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

// Get role
$role = $_POST['role'] ?? 'all';

if ($role === 'all') {
    $sql = "SELECT * FROM users";
    $result = $conn->query($sql);
} else {
    $stmt = $conn->prepare("SELECT * FROM users WHERE role = ?");
    $stmt->bind_param("s", $role);
    $stmt->execute();
    $result = $stmt->get_result();
}

if (!$result) {
    die("Query failed: " . $conn->error);
}

// Admin name and date
$adminName = $_SESSION['full_name'] ?? $_SESSION['username'];
$printDate = date('Y-m-d H:i:s');

// Logo
$logoPath = __DIR__ . '/../../images/hosplogo-hp.png';
$logoBase64 = '';
if (file_exists($logoPath)) {
    $logoData = base64_encode(file_get_contents($logoPath));
    $logoBase64 = 'data:image/png;base64,' . $logoData;
}

$html = '
<style>
    @page {
        margin: 120px 50px 80px 50px;
    }

    body {
        font-family: Arial, sans-serif;
        font-size: 12px;
        position: relative;
        margin-top: 40px; /* Make space for header */
        counter-reset: page;
    }

    .header {
        position: fixed;
        top: -100px;
        left: 0;
        right: 0;
        text-align: center;
    }

    .header img {
        width: 200px;
        margin-bottom: 5px;
    }

    .footer {
        position: fixed;
        bottom: -60px;
        left: 0;
        right: 0;
        height: 50px;
        text-align: center;
        font-size: 10px;
        color: #555;
    }

    .footer .pagenum:before {
        content: "Page " counter(page);
    }

    .watermark {
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%) rotate(-45deg);
        font-size: 75px;
        color: rgba(200, 200, 200, 0.3);
        z-index: -1;
        white-space: nowrap;
    }

    table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
    }

    th, td {
        border: 1px solid #000;
        padding: 5px;
        text-align: left;
    }
</style>

<div class="watermark">CHART MEMORIAL HOSPITAL</div>

<div class="header">
    <img src="' . $logoBase64 . '" alt="Hospital Logo"><br>
    <strong>Generated by:</strong> ' . htmlspecialchars($adminName) . '<br>
    <strong>Date:</strong> ' . $printDate . '<br>
    <h2>Employees List - ' . ucfirst($role) . '</h2>
</div>

<div class="footer">
    <span class="pagenum"></span>
</div>



<div class="body-content">
<table>
    <tr>
        <th>User ID</th>
        <th>Username</th>
        <th>Full Name</th>
        <th>Email</th>
        <th>Role</th>
    </tr>';

while ($row = $result->fetch_assoc()) {
    $html .= '
    <tr>
        <td>' . htmlspecialchars($row['UserID']) . '</td>
        <td>' . htmlspecialchars($row['username']) . '</td>
        <td>' . htmlspecialchars($row['full_name']) . '</td>
        <td>' . htmlspecialchars($row['email']) . '</td>
        <td>' . htmlspecialchars($row['role']) . '</td>
    </tr>';
}

$html .= '</table></div>';

$options = new Options();
$options->set('isHtml5ParserEnabled', true);
$options->set('isPhpEnabled', true);

$dompdf = new Dompdf($options);
$dompdf->setOptions($options);

$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'landscape');
$dompdf->render();
$dompdf->stream("user_report.pdf", ["Attachment" => 0]);
exit();
?>