<?php
session_start();
require '../../dompdf/autoload.inc.php';
use Dompdf\Dompdf;

include('../../config/db.php');

// Ensure the user is an admin
if (!isset($_SESSION['username']) || $_SESSION['role'] !== 'Admin') {
    die("Access denied.");
}

if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

// Get role from POST (from filter dropdown)
$role = $_POST['role'] ?? 'all';

// Filter query based on role
if ($role === 'all') {
    $sql = "SELECT * FROM users";
    $result = $conn->query($sql);
} else {
    $stmt = $conn->prepare("SELECT * FROM users WHERE role = ?");
    $stmt->bind_param("s", $role);
    $stmt->execute();
    $result = $stmt->get_result();
}

// Check for query success
if (!$result) {
    die("Query failed: " . $conn->error);
}

// Get admin name and timestamp
$adminName = $_SESSION['full_name'] ?? $_SESSION['username'];
$printDate = date('Y-m-d H:i:s');

// HTML for PDF
$html = '
<style>
    body { font-family: Arial, sans-serif; font-size: 12px; }
    h2 { text-align: center; }
    table { border-collapse: collapse; width: 100%; }
    th, td { border: 1px solid #000; padding: 5px; text-align: left; }
</style>

<h2>Employees List - ' . ucfirst($role) . '</h2>

<p><strong>Generated by:</strong> ' . htmlspecialchars($adminName) . '<br>
<strong>Date:</strong> ' . $printDate . '</p>

<table>
    <tr>
        <th>User ID</th>
        <th>Username</th>
        <th>Full Name</th>
        <th>Email</th>
        <th>Role</th>
    </tr>';

while ($row = $result->fetch_assoc()) {
    $html .= '
    <tr>
        <td>' . htmlspecialchars($row['UserID']) . '</td>
        <td>' . htmlspecialchars($row['username']) . '</td>
        <td>' . htmlspecialchars($row['full_name']) . '</td>
        <td>' . htmlspecialchars($row['email']) . '</td>
        <td>' . htmlspecialchars($row['role']) . '</td>
    </tr>';
}

$html .= '</table>';

// Create and render PDF
$dompdf = new Dompdf();
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'landscape');
$dompdf->render();

// Output to browser (viewable, not forced download)
$dompdf->stream("user_report.pdf", ["Attachment" => 0]);
exit();
?>
